--- #YAML:1.0
name:               Test-EasyMock
version:            0.01
abstract:           A mock library which is usable easily.
author:
    - keita iseki <keita.iseki+cpan@gmail.com>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Carp:           0
    Data::Dumper:   0
    Exporter:       0
    List::Util:     0
    Scalar::Util:   0
    Test::Builder:  0.98
    Test::More:     0.98
    Test::Tester:   0.108
    version:        0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
